### ISSUE TITLE
How did you get the oh-my-zsh nixpkg to work?

### ISSUE THREAD

**Issue by djvdorp** [NeQuissimus/DevSetup#1]
Sorry for creating this issue for mainly asking a question, but I am trying to use the `oh-my-zsh` nixpkg found [here](https://github.com/NixOS/nixpkgs/tree/master/pkgs/shells/oh-my-zsh), but since I run NixOS 16.03 this is not going to work I think, since it is not in the `release-16.03` branch of the https://github.com/NixOS/nixpkgs repo, but it is in the `master` branch, thanks to you and @scolobb.
I would like to use the `oh-my-zsh` nixpkg as well, but I am unsure on completely switching to the `unstable` channel just because of this, so I hope you can help me out how you did this yourself?
Thanks for your time and effort!

**Comment by scolobb** [comment]
Hey @djvdorp ! I would recommend `git clone`ing the master branch of the main repo and then using the commands from https://nixos.org/wiki/Create_and_debug_nix_packages#How_to_install_from_the_local_repository to install packages from it.

Don't hesitate to ask further questions :-)

**Comment by NeQuissimus** [comment]
What @scolobb said :-) 

Check out the master branch, cd into it, run `nix-build -A oh-my-zsh`, then `nix-env -f . -i oh-my-zsh`. 
The first command will make sure everything builds properly for you, the second one will essentially install into your environment.

The other option would be to switch your NixOS channel to unstable. But then your entire system will update from there rather than the 16.03 channel.

**Comment by djvdorp** [comment]
Thanks a lot for your kind replies and feedback @NeQuissimus @scolobb ! Much appreciated. Does any of you have experience running the `unstable` NixOS channel, and if so, would you like to share experiences and/or advice about that too?

**Comment by NeQuissimus** [comment]
I always use the unstable channel on my home laptop. I have only ever once had an issue with that.
At work, I stick with the stable channel, although I tend to manually pull in packages from git (some of the packages I have contributed where solely because I needed them at work).
